[package]
name = "metaphor-apk-rs"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
lz4_flex = "0.11.5"